import { Roles } from "./constants";

export const paths = {
  home: {
    main: "/",
    ikk: "/ikk",
    infographics: {
      kemiskinan:"/infografik/kemiskinan",
      kelaparan: "/infografik/kelaparan"
    },
    rpjmd: "/rpjmd",
    sdgs: {
      overview: "/sdgs",
      kemiskinan: "/sdgs/mengurangi-kemiskinan",
      kelaparan: "/sdgs/mengakhiri-kelaparan",
      kesehatan: "/sdgs/kesehatan-kesejahteraan",
      pendidikan: "/sdgs/pendidikan-bermutu",
      gender: "/sdgs/kesetaraan-gender",
      airbersih: "/sdgs/airbersih-sanitasi",
      energi: "/sdgs/energibersih-terjangkau",
      ekonomi: "/sdgs/pekerjaan-pertumbuhan-ekonomi",
      inovasi: "/sdgs/infrastruktur-industri-inovasi",
      ketimpangan: "/sdgs/mengurangi-ketimpangan",
      kota: "/sdgs/kota-komunitas-berkelanjutan",
      konsumsi: "/sdgs/konsumsi-produksi",
      iklim: "/sdgs/penanganan-perubahan-iklim",
      laut: "/sdgs/ekosistem-laut",
      darat: "/sdgs/ekosistem-darat",
      perdamaian: "/sdgs/perdamaian",
      kemitraan: "/sdgs/kemitraan-tujuan",
    },
    regulations: "/regulations",
    about: "/about",
  },
  auth: {
    signIn: "/sign-in",
    signUp: "/sign-up",
    resetPassword: "/reset-password",
    updatePassword: "/update-password",
  },
  dashboard: "/dashboard",
};

export const routes = {
  "home.main": { path: paths.home.main, roles: [Roles.All] },
  "home.ikk": { path: paths.home.ikk, roles: [Roles.All] },
  "home.infografik-kelarapan": { path: paths.home.infographics.kelaparan, roles: [Roles.All] },
  "home.infografik-kemiskinan": { path: paths.home.infographics.kemiskinan, roles: [Roles.All] },
  "home.rpjmd": { path: paths.home.rpjmd, roles: [Roles.All] },
  "home.sdgs": { path: paths.home.sdgs.overview, roles: [Roles.All] },
  "home.sdgs-kemiskinan": { path: paths.home.sdgs.kemiskinan, roles: [Roles.All] },
  "home.sdgs-kelaparan": { path: paths.home.sdgs.kelaparan, roles: [Roles.All] },
  "home.sdgs-kesehatan": { path: paths.home.sdgs.kesehatan, roles: [Roles.All] },
  "home.sdgs-pendidikan": { path: paths.home.sdgs.pendidikan, roles: [Roles.All] },
  "home.sdgs-gender": { path: paths.home.sdgs.gender, roles: [Roles.All] },
  "home.sdgs-airbersih": { path: paths.home.sdgs.airbersih, roles: [Roles.All] },
  "home.sdgs-energi": { path: paths.home.sdgs.energi, roles: [Roles.All] },
  "home.sdgs-ekonomi": { path: paths.home.sdgs.ekonomi, roles: [Roles.All] },
  "home.sdgs-inovasi": { path: paths.home.sdgs.inovasi, roles: [Roles.All] },
  "home.sdgs-ketimpangan": { path: paths.home.sdgs.ketimpangan, roles: [Roles.All] },
  "home.sdgs-kota": { path: paths.home.sdgs.kota, roles: [Roles.All] },
  "home.sdgs-konsumsi": { path: paths.home.sdgs.konsumsi, roles: [Roles.All] },
  "home.sdgs-iklim": { path: paths.home.sdgs.iklim, roles: [Roles.All] },
  "home.sdgs-laut": { path: paths.home.sdgs.laut, roles: [Roles.All] },
  "home.sdgs-darat": { path: paths.home.sdgs.darat, roles: [Roles.All] },
  "home.sdgs-perdamaian": { path: paths.home.sdgs.perdamaian, roles: [Roles.All] },
  "home.sdgs-kemitraan": { path: paths.home.sdgs.kemitraan, roles: [Roles.All] },
  "home.regulations": { path: paths.home.regulations, roles: [Roles.All] },
  "home.about": { path: paths.home.about, roles: [Roles.All] },
  "auth.signIn": { path: paths.auth.signIn, roles: [Roles.All] },
  "auth.signUp": { path: paths.auth.signUp, roles: [Roles.All] },
  "auth.resetPassword": { path: paths.auth.resetPassword, roles: [Roles.All] },
  "auth.updatePassword": { path: paths.auth.updatePassword, roles: [Roles.Admin] },
  "dashboard": { path: paths.dashboard, roles: [Roles.Admin] },
};
